Ensure EMAIL_RECIPIENTS is set on staging
When the variable isn't set, mail deliveries will raise:

```
ArgumentError: An SMTP To address is required to send a message. Set the message
smtp_envelope_to, to, cc, or bcc address
```

I could cause head scratching, based on forgetting that staging intercepts
emails.